export const notificationsData = [
  {
    id: 1,
    type: 'income',
    title: 'Salary credited',
    message: '₹95,300 has been credited to your account.',
    time: '2h ago',
    section: 'today',
    read: false,
  },
  {
    id: 2,
    type: 'budget',
    title: 'Entertainment budget exceeded',
    message: 'You have exceeded your entertainment budget by ₹1,850.',
    time: '5h ago',
    section: 'today',
    read: false,
  },
  {
    id: 3,
    type: 'savings',
    title: 'Savings milestone reached',
    message: 'You have saved ₹40,000 this quarter.',
    time: '8h ago',
    section: 'today',
    read: false,
  },
  {
    id: 4,
    type: 'expense',
    title: 'Rent payment completed',
    message: 'Your monthly rent payment of ₹18,000 was successful.',
    time: 'Yesterday',
    section: 'today',
    read: true,
  },
  {
    id: 5,
    type: 'reminder',
    title: 'Electricity bill reminder',
    message: 'Your electricity bill is due in 3 days.',
    time: '2 days ago',
    section: 'week',
    read: false,
  },
  {
    id: 6,
    type: 'expense',
    title: 'Large transaction detected',
    message: 'A shopping expense of ₹4,200 was recorded.',
    time: '3 days ago',
    section: 'week',
    read: true,
  },
  {
    id: 7,
    type: 'budget',
    title: 'Food budget is on track',
    message: 'You have spent 68% of your food budget this month.',
    time: '4 days ago',
    section: 'week',
    read: true,
  },
  {
    id: 8,
    type: 'savings',
    title: 'Cash flow improved',
    message: 'Your savings increased by 12% compared to last month.',
    time: '5 days ago',
    section: 'week',
    read: true,
  },
  {
    id: 9,
    type: 'report',
    title: 'Monthly report available',
    message: 'Your July financial summary is ready to view.',
    time: '1 week ago',
    section: 'earlier',
    read: true,
  },
  {
    id: 10,
    type: 'reminder',
    title: 'Budget reset reminder',
    message: 'Your monthly budget will reset on September 1.',
    time: '2 weeks ago',
    section: 'earlier',
    read: true,
  },
];